# Generated by Django 5.1.4 on 2025-01-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('sqft', models.IntegerField()),
                ('lot_size', models.IntegerField()),
                ('year_built', models.IntegerField()),
                ('days_on_market', models.IntegerField()),
                ('preRating', models.IntegerField()),
                ('postRating', models.IntegerField()),
                ('heating', models.CharField(max_length=200)),
                ('cooling', models.CharField(max_length=200)),
                ('appliances', models.CharField(max_length=200)),
                ('basement', models.CharField(max_length=200)),
                ('fireplace', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='HomeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homes', models.ManyToManyField(to='scraperApp.home')),
            ],
        ),
    ]
