# Generated by Django 5.1.4 on 2025-01-09 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='homelist',
            name='eastCord',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='homelist',
            name='northCord',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='homelist',
            name='southCord',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='homelist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homelist',
            name='westCord',
            field=models.FloatField(default=0),
        ),
    ]
