# Generated by Django 5.1.4 on 2025-01-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0002_homelist_eastcord_homelist_northcord_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homelist',
            old_name='eastCord',
            new_name='east_cord',
        ),
        migrations.RenameField(
            model_name='homelist',
            old_name='northCord',
            new_name='north_cord',
        ),
        migrations.RenameField(
            model_name='homelist',
            old_name='southCord',
            new_name='south_cord',
        ),
        migrations.RenameField(
            model_name='homelist',
            old_name='westCord',
            new_name='west_cord',
        ),
        migrations.AddField(
            model_name='homelist',
            name='max_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homelist',
            name='min_acres',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homelist',
            name='min_baths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homelist',
            name='min_beds',
            field=models.IntegerField(default=0),
        ),
    ]
