# Generated by Django 5.1.4 on 2025-01-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0003_rename_eastcord_homelist_east_cord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homelist',
            name='name',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
