# Generated by Django 5.1.4 on 2025-01-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0004_homelist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='homeUrl',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
