# Generated by Django 5.1.4 on 2025-01-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0005_home_homeurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='appliances',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='home',
            name='homeUrl',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='home',
            name='postRating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='home',
            name='preRating',
            field=models.IntegerField(default=0),
        ),
    ]
