# Generated by Django 5.1.4 on 2025-01-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0006_alter_home_appliances_alter_home_homeurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='homeUrl',
            field=models.URLField(default='', max_length=300),
        ),
    ]
