# Generated by Django 5.1.4 on 2025-01-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0008_homelist_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='thumbnail',
            field=models.ImageField(default='images/default.png', upload_to='images/homes/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='homeUrl',
            field=models.CharField(max_length=300),
        ),
    ]
