# Generated by Django 5.1.4 on 2025-01-10 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0009_home_thumbnail_alter_home_homeurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homelist',
            name='homes',
        ),
        migrations.AddField(
            model_name='homelist',
            name='homes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scraperApp.home'),
            preserve_default=False,
        ),
    ]
