# Generated by Django 5.1.4 on 2025-01-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0010_remove_homelist_homes_homelist_homes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homelist',
            name='homes',
        ),
        migrations.AddField(
            model_name='homelist',
            name='homes',
            field=models.ManyToManyField(to='scraperApp.home'),
        ),
    ]
