# Generated by Django 5.1.4 on 2025-01-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0011_remove_homelist_homes_homelist_homes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='bathrooms',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='homelist',
            name='homes',
            field=models.ManyToManyField(default=None, to='scraperApp.home'),
        ),
        migrations.AlterField(
            model_name='homelist',
            name='min_baths',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='homelist',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
