# Generated by Django 5.1.4 on 2025-01-14 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0012_alter_home_bathrooms_alter_homelist_homes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 14, 5, 20, 54, 545602, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
