# Generated by Django 5.1.4 on 2025-01-14 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0014_remove_home_date_time_homelist_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 14, 5, 29, 17, 303463, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
