# Generated by Django 5.1.4 on 2025-01-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0015_home_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homelist',
            name='east_cord',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='homelist',
            name='north_cord',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='homelist',
            name='south_cord',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='homelist',
            name='west_cord',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=20),
        ),
    ]
