# Generated by Django 5.1.4 on 2025-01-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0016_alter_homelist_east_cord_alter_homelist_north_cord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homelist',
            name='east_cord',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='homelist',
            name='north_cord',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='homelist',
            name='south_cord',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='homelist',
            name='west_cord',
            field=models.FloatField(default=0),
        ),
    ]
