# Generated by Django 5.1.4 on 2025-01-15 03:22

from django.db import migrations

def assign_user_home(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Home = apps.get_model('scraperApp', 'Home')
    user = User.objects.filter(is_superuser=True).first()
    assert user
    Home.objects.all().update(user=user)
class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0018_home_user'),
    ]

    operations = [
        migrations.RunPython(assign_user_home, migrations.RunPython.noop),
    ]
