# Generated by Django 5.1.4 on 2025-01-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0020_home_user_non_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='description',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
