# Generated by Django 5.1.4 on 2025-01-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0022_apikeys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homelist',
            name='min_acres',
            field=models.FloatField(default=0),
        ),
    ]
